### ISSUE TITLE
missing api.client

### ISSUE THREAD

**Issue by jotech** [syncrypt/client#22]
I just updated to 0.3.8 via ``pip install git+https://github.com/syncrypt/client`` but running into problems right now:
```python
syncrypt push
Traceback (most recent call last):
  File "/usr/local/bin/syncrypt", line 10, in <module>
    from syncrypt.app import SyncryptApp
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/__init__.py", line 1, in <module>
    from .syncrypt import SyncryptApp
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 21, in <module>
    from syncrypt.api import SyncryptAPI, APIClient
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/api/__init__.py", line 14, in <module>
    from .client import APIClient
ImportError: No module named 'syncrypt.api.client'
```
Did I miss something during the update?

**Comment by bakkdoor** [comment]
Thanks for the bug report. We'll push a fix tomorrow.

**Comment by bakkdoor** [comment]
@jotech Please try again :)

**Comment by jotech** [comment]
it's working again, many thanks ;)

**Comment by bakkdoor** [comment]
Awesome. Have fun with the latest release :)
