### ISSUE TITLE
Daemon stats API fails after running for long time

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#23]
This happens whenever I've had the daemon running in the background for a longer time without running the GUI. It might be related to resuming from sleep mode, but it could also just be whenever it's been running idle for a while. Not sure yet.
In any case, this causes the GUI to not get the vault's user list in the VaultSettings sidebar.
Might just be happening on Mac OS. Haven't seen this on Windows yet, but that could just be because I don't use Windows very much.

```
2016-11-24 16:16:37 INFO [aiohttp.access] 127.0.0.1 - - [24/Nov/2016:15:16:37 +0000] "GET /v1/stats HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.113 Electron/1.4.3 Safari/537.36"
2016-11-24 16:16:39 DEBUG [syncrypt.backends.binary] Found an available connection!
2016-11-24 16:16:39 INFO [syncrypt.backends.binary] Getting a list of vault users
2016-11-24 16:16:39 ERROR [aiohttp.web] Error handling request
Traceback (most recent call last):
  File "venv/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
  File "venv/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
  File "asyncio/coroutines.py", line 209, in coro
  File "syncrypt/api/resources.py", line 50, in dispatch_list
  File "syncrypt/api/resources.py", line 333, in get_obj_list
  File "syncrypt/backends/binary.py", line 761, in myco
  File "syncrypt/backends/binary.py", line 436, in list_vault_users
  File "syncrypt/backends/binary.py", line 124, in write_term
  File "asyncio/streams.py", line 323, in drain
  File "venv/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
  File "venv/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
  File "asyncio/coroutines.py", line 209, in coro
  File "syncrypt/api/resources.py", line 50, in dispatch_list
  File "syncrypt/api/resources.py", line 333, in get_obj_list
  File "syncrypt/backends/binary.py", line 761, in myco
  File "syncrypt/backends/binary.py", line 436, in list_vault_users
  File "syncrypt/backends/binary.py", line 124, in write_term
  File "asyncio/streams.py", line 323, in drain
  File "venv/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
  File "venv/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
  File "asyncio/coroutines.py", line 209, in coro
  File "syncrypt/api/resources.py", line 50, in dispatch_list
  File "syncrypt/api/resources.py", line 333, in get_obj_list
  File "syncrypt/backends/binary.py", line 761, in myco
  File "syncrypt/backends/binary.py", line 436, in list_vault_users
  File "syncrypt/backends/binary.py", line 124, in write_term
  File "asyncio/streams.py", line 323, in drain
  File "venv/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
  File "venv/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
  File "asyncio/coroutines.py", line 209, in coro
  File "syncrypt/api/resources.py", line 50, in dispatch_list
  File "syncrypt/api/resources.py", line 333, in get_obj_list
  File "syncrypt/backends/binary.py", line 761, in myco
  File "syncrypt/backends/binary.py", line 436, in list_vault_users
  File "syncrypt/backends/binary.py", line 124, in write_term
  File "asyncio/streams.py", line 323, in drain
  File "venv/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
  File "venv/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
  File "asyncio/coroutines.py", line 209, in coro
  File "syncrypt/api/resources.py", line 50, in dispatch_list
  File "syncrypt/api/resources.py", line 333, in get_obj_list
  File "syncrypt/backends/binary.py", line 761, in myco
  File "syncrypt/backends/binary.py", line 436, in list_vault_users
  File "syncrypt/backends/binary.py", line 124, in write_term
  File "asyncio/streams.py", line 323, in drain
  File "venv/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
  File "venv/lib/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
  File "asyncio/coroutines.py", line 209, in coro
  File "syncrypt/api/resources.py", line 50, in dispatch_list
  File "syncrypt/api/resources.py", line 333, in get_obj_list
  File "syncrypt/backends/binary.py", line 761, in myco
  File "syncrypt/backends/binary.py", line 436, in list_vault_users
  File "syncrypt/backends/binary.py", line 124, in write_term
  File "asyncio/streams.py", line 323, in drain
  File "asyncio/tasks.py", line 241, in _step
  File "syncrypt/app/syncrypt.py", line 683, in pull_vault_periodically
  File "syncrypt/app/syncrypt.py", line 697, in pull_vault
  File "syncrypt/app/syncrypt.py", line 622, in retrieve_metadata
  File "syncrypt/backends/binary.py", line 761, in myco
  File "syncrypt/backends/binary.py", line 328, in vault_metadata
  File "syncrypt/backends/binary.py", line 109, in read_response
  File "syncrypt/backends/binary.py", line 81, in read_term
  File "asyncio/streams.py", line 627, in read
  File "asyncio/streams.py", line 457, in _wait_for_data
  File "asyncio/futures.py", line 361, in __iter__
  File "asyncio/tasks.py", line 296, in _wakeup
  File "asyncio/futures.py", line 274, in result
  File "asyncio/selector_events.py", line 669, in _read_ready
TimeoutError: [Errno 60] Operation timed out
```

**Comment by lordi** [comment]
Please confirm wether this has been fixed in master.

We can track exponential backoff in another issue.
