### ISSUE TITLE
Fetching flying vaults while syncing vault fails

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#39]
When syncing a vault with many files and while running e.g. file stat operations, the daemon returns a 500 status when trying to fetch the list of flying vaults.

Exception backtrace:

```
Traceback (most recent call last):
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/__init__.py", line 243, in error_middleware
    response = await handler(request)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 142, in handler_wrapper
    result = yield from result
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/resources.py", line 54, in dispatch_list
    objs = await self.get_obj_list(request)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/resources.py", line 309, in get_obj_list
    my_fingerprint = self.app.identity.get_fingerprint()
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/models/identity.py", line 144, in get_fingerprint
    raise IdentityNotInitialized()
syncrypt.models.identity.IdentityNotInitialized
2018-04-08 19:30:54 [I] 127.0.0.1 [08/Apr/2018:17:30:54 +0000] "GET /v1/flying-vault/ HTTP/1.1" 500 195 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Electron/1.8.3 Safari/537.36"
```

**Comment by bakkdoor** [comment]
Is this still a valid bug or can we close this?

**Comment by lordi** [comment]
I think this bug specifically has been fixed, but flying vaut fetching currently is not enabled in master. I'll close this as soon as flying vaults are fetched.

**Comment by lordi** [comment]
Please re-open in case it still exists
