### ISSUE TITLE
API endpoint for vault bundle import

### ISSUE THREAD

**Issue by lordi** [syncrypt/client#47]

**Comment by bakkdoor** [comment]
I'm getting this error when trying to import a previously exported vault package into an empty folder:

```
2018-05-03 06:49:39 [E] Folder "/private/tmp/deeply nested import" already exists.
Traceback (most recent call last):
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/__init__.py", line 243, in error_middleware
    response = await handler(request)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 142, in handler_wrapper
    result = yield from result
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/resources.py", line 78, in dispatch_post
    obj = await self.post_obj(request)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/resources.py", line 253, in post_obj
    request_dict['import_package'], request_dict['folder'])
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/app/syncrypt.py", line 381, in import_package
    raise ValueError('Folder "{0}" already exists.'.format(target_folder))
ValueError: Folder "/private/tmp/deeply nested import" already exists.
2018-05-03 06:49:39 [I] 127.0.0.1 [03/May/2018:04:49:39 +0000] "POST /v1/vault/ HTTP/1.1" 500 255 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Electron/1.8.3 Safari/537.36"
```
