### ISSUE TITLE
Daemon error when cloning vault with latest master

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#48]
I'm getting the following error when trying to clone a vault:

```
2018-04-23 07:10:24 [W] Continuing without verifying SSL cert
2018-04-23 07:10:24 [D] Connecting to server 127.0.0.1:1337 ssl=True...
2018-04-23 07:10:24 [I] 127.0.0.1 [23/Apr/2018:05:10:24 +0000] "GET /v1/vault/ HTTP/1.1" 200 370 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Electron/1.8.3 Safari/537.36"
2018-04-23 07:10:24 [D] Identifying to server as ('syncrypt', '0.4.3.post0+24.g4f98c66d46')
2018-04-23 07:10:24 [D] Connected (client: 0.4.3.post0+24.g4f98c66d46; server; 0.11.0)
2018-04-23 07:10:24 [D] Choosing <Connection 0x10d11eeb8 busy>
2018-04-23 07:10:24 [D] Logged in to server (version 0.11.0)
2018-04-23 07:10:24 [I] Retrieving encrypted key for vault 10cce746-8ff7-4d6d-a1c4-6c65bc0e2696 (Fingerprint: d2:cd:46:ea:6c:40:8f:2e)
2018-04-23 07:10:24 [D] Found an available connection <Connection 0x10d11eeb8 busy>
2018-04-23 07:10:24 [D] Decrypting block size: 512 bytes
2018-04-23 07:10:24 [D] RSA Decrypted 512 -> 470 bytes
2018-04-23 07:10:24 [D] RSA Decrypted 512 -> 470 bytes
2018-04-23 07:10:24 [D] RSA Decrypted 512 -> 470 bytes
2018-04-23 07:10:24 [D] RSA Decrypted 512 -> 470 bytes
2018-04-23 07:10:25 [D] RSA Decrypted 512 -> 470 bytes
2018-04-23 07:10:25 [D] RSA Decrypted 512 -> 470 bytes
2018-04-23 07:10:25 [D] RSA Decrypted 512 -> 470 bytes
2018-04-23 07:10:25 [D] RSA Decrypted 512 -> 155 bytes
2018-04-23 07:10:25 [I] Creating vault from package in /private/tmp/deeply nested
2018-04-23 07:10:25 [D] Directory exists, checking if empty
2018-04-23 07:10:25 [E]
Traceback (most recent call last):
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/__init__.py", line 243, in error_middleware
    response = await handler(request)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 142, in handler_wrapper
    result = yield from result
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/resources.py", line 78, in dispatch_post
    obj = await self.post_obj(request)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/api/resources.py", line 249, in post_obj
    vault = await self.app.clone(request_dict['id'], request_dict['folder'])
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/app/syncrypt.py", line 375, in clone
    await self.retrieve_metadata(vault)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/app/syncrypt.py", line 442, in retrieve_metadata
    await vault.backend.open()
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.5/site-packages/syncrypt/backends/binary.py", line 937, in open
    raise VaultNotInitialized()
syncrypt.exceptions.VaultNotInitialized
2018-04-23 07:10:25 [I] 127.0.0.1 [23/Apr/2018:05:10:25 +0000] "POST /v1/vault/ HTTP/1.1" 500 195 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Electron/1.8.3 Safari/537.36"
2018-04-23 07:10:25 [I] 127.0.0.1 [23/Apr/2018:05:10:25 +0000] "GET /v1/stats/ HTTP/1.1" 200 504 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Electron/1.8.3 Safari/537.36"
2018-04-23 07:10:25 [I] Refreshing vault information
2018-04-23 07:10:25 [D] Found an available connection <Connection 0x10d11eeb8 busy>
```

I see the following vault card in the UI afterwards:

![screen shot 2018-04-23 at 07 12 45](https://user-images.githubusercontent.com/17142/39107963-eaac9ba4-46c5-11e8-8341-75410750325b.png)

Also, when opening the vault dialog for that "empty" vault I can view the vault's history log but it doesn't show any other metadata and also doesn't sync any files.

Let me know if you want me to test anything or whatever. I've reproduced this with different vaults. Always getting the same error. This is happening with latest master on mac OS.

**Comment by lordi** [comment]
Can not reproduce. Can you try with cli: ``syncrypt clone -l DEBUG <id> <dir>`` ?

**Comment by bakkdoor** [comment]
OK I think this was an issue with my local server. Closing this for now. Will reopen if I run into it again.
