### ISSUE TITLE
error pushing files

### ISSUE THREAD

**Issue by jotech** [syncrypt/client#5]
I'm getting an error while pushing my vault to the server.
It seems to be an encoding problem. Data is a diverse set of html and pdf files.

``` python
INFO:syncrypt.backends.binary:Uploading bundle (metadata: 512 bytes, content: 144 bytes)
Traceback (most recent call last):
  File "/usr/local/bin/syncrypt", line 266, in <module>
    c.run()
  File "/usr/local/bin/syncrypt", line 153, in run
    self.loop.run_until_complete(self.app.push())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 388, in push
    for bundle in vault.walk_disk():
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/models/vault.py", line 156, in walk_disk
    yield self.bundle_for(relpath)
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/models/vault.py", line 182, in bundle_for
    Bundle(os.path.join(self.folder, relpath), vault=self)
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/models/bundle.py", line 36, in __init__
    h.update(self.relpath.encode(self.vault.config.encoding))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcfc' in position 32: surrogates not allowed
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:447> wait_for=<Future pending cb=[Task._wakeup()]> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
Exception ignored in: <generator object SyncryptApp._push_bundle at 0x7fc4780584c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 447, in _push_bundle
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 634, in upload
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 227, in __exit__
  File "/usr/lib/python3.5/asyncio/locks.py", line 242, in set
  File "/usr/lib/python3.5/asyncio/futures.py", line 332, in set_result
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:447> wait_for=<Future pending cb=[Task._wakeup()]> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
Exception ignored in: <generator object SyncryptApp._push_bundle at 0x7fc47806f728>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 447, in _push_bundle
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 634, in upload
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 227, in __exit__
  File "/usr/lib/python3.5/asyncio/locks.py", line 242, in set
  File "/usr/lib/python3.5/asyncio/futures.py", line 332, in set_result
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:442> wait_for=<Future pending cb=[Task._wakeup()]> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
Exception ignored in: <generator object SyncryptApp._push_bundle at 0x7fc47806f0a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 442, in _push_bundle
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 615, in stat
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 227, in __exit__
  File "/usr/lib/python3.5/asyncio/locks.py", line 242, in set
  File "/usr/lib/python3.5/asyncio/futures.py", line 332, in set_result
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future finished result=True> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future finished result=True> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future finished result=True> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:447> wait_for=<Future finished result=b'GIF89a\x10\...xe7K\x01\x00;'> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
Exception ignored in: <generator object SyncryptApp._push_bundle at 0x7fc4780665c8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 447, in _push_bundle
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 634, in upload
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 271, in upload
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
  File "/usr/local/lib/python3.5/dist-packages/syncrypt/pipes/io.py", line 40, in close
  File "/usr/local/lib/python3.5/dist-packages/aiofiles/threadpool/utils.py", line 36, in method
  File "/usr/lib/python3.5/asyncio/base_events.py", line 542, in run_in_executor
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:439> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:442> wait_for=<Future pending cb=[Task._wakeup()]> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:442> wait_for=<Future pending cb=[Task._wakeup()]> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
ERROR:syncrypt.app.syncrypt:(<_UnixSelectorEventLoop running=False closed=True debug=False>, {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<SyncryptApp._push_bundle() running at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:442> wait_for=<Future pending cb=[Task._wakeup()]> cb=[SyncryptApp.push_bundle.<locals>.cb() at /usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py:149]>}), {}
```

**Comment by lordi** [comment]
Thanks, this is an unexpected character in the filename.
I will see if I can write a test that will test this condition. Looks like passing `surrogateescape` to the encode/decode function might help:
http://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s

**Comment by jotech** [comment]
Thanks, I just tried your fix and now this file could be uploaded.
But now I'm getting some warnings:

``` python
WARNING:syncrypt.app.syncrypt:Got exception:  <class 'syncrypt.backends.binary.ConnectionResetException'> ['  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step\n    result = coro.send(None)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 473, in _push_bundle\n    yield from bundle.vault.backend.stat(bundle)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 611, in stat\n    stat_info = yield from conn.stat(bundle)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 235, in stat\n    response = yield from self.read_term()\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 62, in read_term\n    raise ConnectionResetException()\n']
WARNING:syncrypt.app.syncrypt:Got exception:  <class 'syncrypt.backends.binary.ConnectionResetException'> ['  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step\n    result = coro.send(None)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 478, in _push_bundle\n    yield from bundle.vault.backend.upload(bundle)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 634, in upload\n    yield from conn.upload(bundle)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 280, in upload\n    response = yield from self.read_response()\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 85, in read_response\n    decoded = yield from self.read_term(assert_ok=True)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 62, in read_term\n    raise ConnectionResetException()\n']
WARNING:syncrypt.app.syncrypt:Got exception: Connection lost <class 'ConnectionResetError'> ['  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step\n    result = coro.send(None)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/app/syncrypt.py", line 473, in _push_bundle\n    yield from bundle.vault.backend.stat(bundle)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 611, in stat\n    stat_info = yield from conn.stat(bundle)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 233, in stat\n    yield from self.write_term(\'stat\', bundle.store_hash)\n', '  File "/usr/local/lib/python3.5/dist-packages/syncrypt/backends/binary.py", line 100, in write_term\n    yield from self.writer.drain()\n', '  File "/usr/lib/python3.5/asyncio/streams.py", line 333, in drain\n    yield from self._protocol._drain_helper()\n', '  File "/usr/lib/python3.5/asyncio/streams.py", line 204, in _drain_helper\n    raise ConnectionResetError(\'Connection lost\')\n']
```

The connection lost warning is repreated several times then syncrypt seems to hang with no cpu load.

**Comment by bakkdoor** [comment]
Have you tried re-running `syncrypt push`?

**Comment by jotech** [comment]
you are right, never mind ;)
