### ISSUE TITLE
Switching language crashes daemon

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#53]
When switching the language in the Desktop in the Settings Dialog it seems to crash the daemon.

Here's a backtrace:

```
2019-07-03 03:46:56 [E] Uncaught exception, restarting daemon...
Traceback (most recent call last):
  File "/Users/bakkdoor/projects/syncrypt/client/scripts/syncrypt_daemon", line 79, in run_syncrypt
    will_restart = app.restart_flag
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/Users/bakkdoor/projects/syncrypt/client/syncrypt/api/__init__.py", line 379, in start
    await trio_asyncio.aio_as_trio(site.stop)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/async_generator/_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio_asyncio/async_.py", line 131, in open_loop
    current_policy.reset(old_policy)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
TypeError: trio.run received unrecognized yield message <Future pending cb=[_TrioHandle._cb_future_cancel()]>. Are you trying to use a library written for some other framework like asyncio? That won't work without some kind of compatibility shim.
2019-07-03 03:46:58 [E] Uncaught exception, restarting daemon...
Traceback (most recent call last):
  File "/Users/bakkdoor/projects/syncrypt/client/scripts/syncrypt_daemon", line 79, in run_syncrypt
    will_restart = app.restart_flag
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/Users/bakkdoor/projects/syncrypt/client/syncrypt/api/__init__.py", line 374, in start
    await trio_asyncio.aio_as_trio(site.start)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio_asyncio/base.py", line 229, in run_aio_coroutine
    return await run_aio_future(coro)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio_asyncio/util.py", line 39, in run_aio_future
    res = await trio.hazmat.wait_task_rescheduled(abort_cb)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/outcome/_sync.py", line 111, in unwrap
    raise captured_error
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/aiohttp/web_runner.py", line 102, in start
    reuse_port=self._reuse_port)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 28080): address already in use
2019-07-03 03:47:00 [E] Uncaught exception, restarting daemon...
Traceback (most recent call last):
  File "/Users/bakkdoor/projects/syncrypt/client/scripts/syncrypt_daemon", line 79, in run_syncrypt
    will_restart = app.restart_flag
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio/_core/_run.py", line 506, in __aexit__
    raise combined_error_from_nursery
  File "/Users/bakkdoor/projects/syncrypt/client/syncrypt/api/__init__.py", line 374, in start
    await trio_asyncio.aio_as_trio(site.start)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio_asyncio/base.py", line 229, in run_aio_coroutine
    return await run_aio_future(coro)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio_asyncio/util.py", line 39, in run_aio_future
    res = await trio.hazmat.wait_task_rescheduled(abort_cb)
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/outcome/_sync.py", line 111, in unwrap
    raise captured_error
  File "/Users/bakkdoor/projects/syncrypt/client/lib/python3.7/site-packages/aiohttp/web_runner.py", line 102, in start
    reuse_port=self._reuse_port)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 28080): address already in use
```

**Comment by bakkdoor** [comment]
This also happens in the SetupWizard it seems. Basically any time the daemon attempts to store the new language in the config I think.

**Comment by lordi** [comment]
:+1:
