### ISSUE TITLE
Daemon error during startup

### ISSUE THREAD

**Issue by bakkdoor** [syncrypt/client#55]
Got this error during daemon startup:

```
2019-10-15 09:25:22 DEBUG [syncrypt.backends.binary] Logged in to server (version 0.11.0)
2019-10-15 09:25:22 DEBUG [syncrypt.backends.binary] Found an available connection for <Vault: /private/tmp/test-vault-mit-hannes>
2019-10-15 09:25:22 INFO [syncrypt.backends.binary] Getting a list of changes for <Vault: /private/tmp/test-vault-mit-hannes> (9eadcd00-40f7-492d-8411-3be1207ae217 to latest)
2019-10-15 09:25:22 INFO [aiohttp.access] 127.0.0.1 [15/Oct/2019:07:25:21 +0000] "GET /v1/auth/user/ HTTP/1.1" 200 454 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Syncrypt/0.5.2 Chrome/56.0.2924.87 Electron/1.6.2 Safari/537.36"
2019-10-15 09:25:22 DEBUG [syncrypt.app.vault] State transition: VaultState.UNINITIALIZED -> VaultState.READY
2019-10-15 09:25:22 DEBUG [syncrypt.app.vault] State transition: VaultState.READY -> VaultState.SYNCING
2019-10-15 09:25:22 DEBUG [syncrypt.app.vault] State transition: VaultState.SYNCING -> VaultState.READY
2019-10-15 09:25:22 DEBUG [syncrypt.app.vault] respond_to_file_changes started
2019-10-15 09:25:22 DEBUG [syncrypt.app.vault] watchdog_task started
2019-10-15 09:25:22 INFO [syncrypt.app.vault] Auto-pulling /private/tmp/test-vault-mit-hannes every 10 seconds
2019-10-15 09:25:22 DEBUG [syncrypt.backends.binary] Found an available connection <Connection 0x10fab1e10 busy>
2019-10-15 09:25:22 INFO [syncrypt.backends.binary] Getting a list of vaults by fingerprint: d2cd46ea6c408f2e
2019-10-15 09:25:22 DEBUG [syncrypt.managers.flying_vault] Received vault: 2424ca38-a56a-4c33-8d8d-739fab3a0a62 (with metadata)
2019-10-15 09:25:22 DEBUG [syncrypt.pipes.crypto] Decrypting block size: 512 bytes
2019-10-15 09:25:23 ERROR [syncrypt.app.daemon] Exception while refreshing flying vaults
Traceback (most recent call last):
  File "syncrypt/app/daemon.py", line 100, in refresh_flying_vaults_periodically
  File "syncrypt/managers/flying_vault.py", line 61, in update
  File "syncrypt/app/syncrypt.py", line 366, in _decrypt_metadata
  File "syncrypt/pipes/base.py", line 31, in readall
  File "syncrypt/pipes/crypto.py", line 210, in read
  File "Cryptodome/Cipher/PKCS1_OAEP.py", line 175, in decrypt
  File "Cryptodome/Hash/SHA1.py", line 158, in new
  File "Cryptodome/Hash/SHA1.py", line 74, in __init__
  File "ctypes/__init__.py", line 361, in __getattr__
  File "ctypes/__init__.py", line 366, in __getitem__
AttributeError: dlsym(0x7fb14cc857e0, SHA1_init): symbol not found
2019-10-15 09:25:25 INFO [aiohttp.access] 127.0.0.1 [15/Oct/2019:07:25:25 +0000] "GET /v1/vault/ HTTP/1.1" 200 1042 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Syncrypt/0.5.2 Chrome/56.0.2924.87 Electron/1.6.2 Safari/537.36"
```

**Comment by bakkdoor** [comment]
Noticed this error in the daemon logs. I can see this error happening multiple times, it seems to be repeatedly happening with the same backtrace.

**Comment by lordi** [comment]
Does this happen only with the OS X build or also when you install & run the daemon via Python?

**Comment by bakkdoor** [comment]
When I just run it from the source repo (using python) I don't get the error.

**Comment by bakkdoor** [comment]
When I run it from `dist/` (after building it via `setup.py`) i get the same error:

```
$ dist/syncrypt_daemon
/var/folders/kl/3xqxcxw14sv94y6h93z5crp40000gn/T/_MEIgngrzv/trio_asyncio/base.py:585: TrioDeprecationWarning: trio.open_cancel_scope is deprecated since Trio 0.10.0; use trio.CancelScope instead (https://github.com/python-trio/trio/issues/607)
2019-10-17 08:35:28 [I] REST API Server started at http://127.0.0.1:28080
2019-10-17 08:35:28 [I] Registering vault <Vault: /private/tmp/test-vault-mit-hannes>
2019-10-17 08:35:28 [I] Pulling <Vault: /private/tmp/test-vault-mit-hannes>
2019-10-17 08:35:28 [I] Updating flying vaults...
2019-10-17 08:35:30 [I] Getting a list of changes for <Vault: /private/tmp/test-vault-mit-hannes> (9eadcd00-40f7-492d-8411-3be1207ae217 to latest)
2019-10-17 08:35:30 [I] Getting a list of vaults
2019-10-17 08:35:30 [I] Getting a list of vaults
2019-10-17 08:35:30 [I] Auto-pulling /private/tmp/test-vault-mit-hannes every 10 seconds
2019-10-17 08:35:30 [I] Getting a list of vaults by fingerprint: d2cd46ea6c408f2e
2019-10-17 08:35:30 [E] Exception while refreshing flying vaults
Traceback (most recent call last):
  File "syncrypt/app/daemon.py", line 100, in refresh_flying_vaults_periodically
    await self.flying_vaults.update()
  File "syncrypt/managers/flying_vault.py", line 61, in update
    encrypted_metadata, user_vault_key
  File "syncrypt/app/syncrypt.py", line 366, in _decrypt_metadata
    package_info = await export_pipe.readall()
  File "syncrypt/pipes/base.py", line 31, in readall
    new_data = await self.read()
  File "syncrypt/pipes/crypto.py", line 210, in read
    dec_data = self.cipher.decrypt(data)
  File "site-packages/Cryptodome/Cipher/PKCS1_OAEP.py", line 175, in decrypt
  File "site-packages/Cryptodome/Hash/SHA1.py", line 158, in new
  File "site-packages/Cryptodome/Hash/SHA1.py", line 74, in __init__
  File "ctypes/__init__.py", line 369, in __getattr__
  File "ctypes/__init__.py", line 374, in __getitem__
AttributeError: dlsym(0x7fce79c67ab0, SHA1_init): symbol not found
```

**Comment by lordi** [comment]
https://github.com/Legrandin/pycryptodome/issues/281

**Comment by lordi** [comment]
No replies there for 5 months, I'll look into it a bit more

**Comment by lordi** [comment]
@bakkdoor please try the `pyinstaller-bump` branch or build. Please provider PyInstallier log if it still fails.
